name: Release Workflow

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest

    # This workflow only runs when a release pull request is merged into main
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.base_ref == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Publish package versions
        run: yarn changeset publish