name: Release Workflow

on:
  push:
    branches:
      - main

env:
  VSCE_PAT: ${{ secrets.VSCE_PAT }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  npm_config_registry: "https://registry.npmjs.org"

jobs:
  publish-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install the packages
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Build the code
        run: yarn build
        env:
          NODE_ENV: production

      - name: Get Date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"

      - name: Open PR for new release or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: yarn changeset publish
          version: yarn release
          title: 'Theme Tools Release'
          commit: Theme Tools Release: ${{ steps.date.outputs.date }}
          createGithubRelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: VS Code Marketplace publish
        if: |
          steps.changesets.outputs.published == 'true' &&
          contains(
            fromJSON(steps.changesets.outputs.publishedPackages.*.name),
            'theme-check-vscode'
          ))
        run: yarn publish:vsce
