name: Release Workflow

on:
  pull_request:
    types: [closed]

jobs:
  publish-packages:
    runs-on: ubuntu-latest

    # This workflow only runs when a release pull request is merged into main
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/') && github.base_ref == 'main'
    steps:
      - name: Placeholder
        run: |
          echo "This is a placeholder workflow. Once we open source the project, we can enable the workflow below."
          echo "For more details, please refer to https://github.com/Shopify/theme-tools/issues/46"
      # - uses: actions/checkout@v3
      #   with:
      #     submodules: true

      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 16
      #     cache: 'yarn'

      # - name: Install the packages
      #   run: yarn install --frozen-lockfile --ignore-engines

      # - name: Build the code
      #   run: yarn build:ci
      #   env:
      #     NODE_ENV: production

      # - name: Publish packages
      #   run: yarn changeset publish
