name: Release Workflow

on: workflow_dispatch

env:
  VSCE_PAT: ${{ secrets.VSCE_PAT }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  publish-packages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"

      - name: Install the packages
        run: yarn install --frozen-lockfile --ignore-engines

      - name: Build the code
        run: yarn build:ci
        env:
          NODE_ENV: production

      - name: NPM publish
        run: yarn changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push tags
        run: git push --follow-tags

      - name: VS Code Marketplace publish
        run: yarn publish:vsce
